CHANGELOG.md
project.clj

Version bump associated with [#1]

Bump to v.1.3.0 and update changelog

---

CHANGELOG.md
project.clj

Version bump and changelog
Low, the change was validated in #5 
- bump the patch version once more and rollback #5

Version 1.3.1

---

CHANGELOG.md
project.clj

bump to 1.4.0

---

CHANGELOG.md
project.clj

bump to 1.4.2

---

CHANGELOG.md
project.clj

Version bump for #18 
- See #18 
- See #18 
- revert #18 and bump the version

Bump to v1.4.5, update changelog

---

CHANGELOG.md
project.clj

Bump to v1.5.0

---

CHANGELOG.md
project.clj

Bump to v1.5.1

---

CHANGELOG.md
project.clj

bump to 1.6.1

---

CHANGELOG.md
project.clj

Version bump and changelog for #33 
- N/A
Low, version bump
- revert #33, bump version and re-release

Version 1.6.2 and changelog

---

CHANGELOG.md
project.clj

Bump to v1.6.3 and update the changelog.

Bump to v1.6.3

---

CHANGELOG.md
project.clj

Version bump to 1.6.4 for #50 
- Accounted for in #50 
Accounted for in #50 
- revert #50, bump patch, re-release

Version 1.6.4

---

.circleci/config.yml

Notify #sources on failures in both build and test steps.

add notify-on-failure to build step

---

CHANGELOG.md
project.clj

Quote the replication key in incremental queries. #59 
- Created new tests

Bump to v1.6.9 and update changelog

---

spikes/005-central-concept/tap-const/src/tap_const/core.clj
spikes/006-permissions/tap-const/src/tap_const/core.clj
spikes/008-how-to-read-cdc-log/tap-const/src/tap_const/core.clj
spikes/011-initial-full-table-to-cdc-transition-strategy/tap-const/src/tap_const/core.clj
src/tap_mssql/core.clj

This PR updates the `nrepl` host to be `127.0.0.1`.

Replace `0.0.0.0` with `127.0.0.1`

---

.circleci/config.yml

Update the .circleci file to use new minimal `run-test` 
low 

Use new run-test pattern from latest tap-tester

---

tests/database.py

https://jira.talendforge.org/browse/TDL-15065

fail with a list of dependencies if unable to connect to db

---

project.clj
src/tap_mssql/core.clj

This reverts commit 959191ed9ec8f20e444757b695dde7e9d42481b9.

Revert "Update log4j using singer-clojure for TDL-21424"

---

CHANGELOG.md

Fixes broken changelog links.
None. Changelog update.

Update changelog urls to reference singer repo.

---

CHANGELOG.md
project.clj

Version bump and changelog update to go with [PR 86](https://github.com/singer-io/tap-mssql/pull/86)
Must be released with PR 86

TDL-21551 Version Bump and Changelog

---

.circleci/config.yml
project.clj
src/tap_mssql/catalog.clj

See #92 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code

Fix arm parseDouble schema issue
