singer-io/tap-mssql

src/tap_mssql/catalog.clj
https://stitchdata.atlassian.net/browse/SUP-902
According to [this documentation](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-partitions-transact-sql?view=sql-server-ver15), the `rows` column in `sys.partitions` is a bigint, so the cast to `int` could fail on very large tables. This PR changes it to cast to `bigint`.
Very low risk, since bigint is a superset of int.
=> Discover row count as bigint

CHANGELOG.md, project.clj
Version Bump
This PR: Low, risks tested and described in #8 
- Roll back #8 and bump the version again
=> Updated version to 1.4.1

src/tap_mssql/config.clj, test/tap_mssql/discover_config_test.clj
When the database key exists but maps to a nil value, this returns incorrectly. In the absence of a specific dbname, jdbc expects this to be an empty string.
=> Extract database key and if nil return an empty string

src/tap_mssql/singer/transform.clj, test/tap_mssql/core_sync_test.clj
During discovery, for columns of type `binary` the tap writes the schema as a string, but does not transform the data to a string, instead emitting it as a byte array.
This PR changes the tap to transform columns of type `binary` to a hex string.
=> transform binary types to hex strings

CHANGELOG.md, project.clj
=> bump version to 1.4.4

src/tap_mssql/sync_strategies/logical.clj, test/tap_mssql/sync_log_based_test.clj
https://stitchdata.atlassian.net/browse/SUP-1168
- We ran the unit tests and observed `_sdc_deleted_at` populate when we tried to `get` a bad key (like `"commit_time2"`)
- Low, seems to be a rare case that `"commit_time"` is `null`
=> SUP-1168: Fallback to time now for sdc_deleted_at

src/tap_mssql/sync_strategies/logical.clj, test/tap_mssql/sync_log_based_test.clj
In logical replication, sometimes our query here returns `nil`
https://github.com/singer-io/tap-mssql/blob/1bfc58de63a695512c74c57a32710d450866ae07/src/tap_mssql/sync_strategies/logical.clj#L95-L99
And when that happens, the tap will eventually try `(> nil 12345)` which causes a `java.lang.NullPointerException`. 
- Ran the tap
- Low
=> Throw an error if min_valid_version is null

.circleci/config.yml, src/tap_mssql/sync_strategies/common.clj, src/tap_mssql/sync_strategies/full.clj, src/tap_mssql/sync_strategies/incremental.clj, src/tap_mssql/sync_strategies/logical.clj
To avoid certain types of row locking, we should define the cursor type and concurrency policy for our ResultSet objects.
=> Use a read-only cursor

CHANGELOG.md, project.clj
Releases the 1.6.0 changes to use a read-only, forward cursor on ResultSets
Confirmed that this alleviates the lock contention.
=> Bump to 1.6.0

src/tap_mssql/singer/bookmarks.clj, src/tap_mssql/singer/messages.clj, test/tap_mssql/sync_interruptible_full_table_test.clj
A View can be synced with or without `view-key-properties` being set. If interrupted without `view-key-properties`, it should not emit a bad state. If interrupted with `view-key-properties` set, it should be resumable.
=> Fix bugs with a View being interrupted while syncing

project.clj
No functional changes, this PR replaces the default `lein` generated license key/value in `project.clj` with AGPL to match the repository.
- N/A
Low, this is just a metadata change to the file.
=> Update project's license to match repo's license

src/tap_mssql/sync_strategies/logical.clj
Co-authored-by: kamd
Same as #31 but brought into a branch on this PR so circleCI will run.
> Fixed #30, problem with incremental sync strategy database_id mismatch in Azure SQL.
> 
> DB_NAME can give inconsistent results with the database_ids from sys.change_tracking_databases on Azure SQL, this fix joins with sys.databases instead.
Ran this branch against an azure database that the tap was finding as not having change tracking enabled despite it being enabled.
=> Get the correct change tracking information in azure

src/tap_mssql/config.clj
Add ApplicationIntent=ReadOnly to connection string
=> Add ApplicationIntent=ReadOnly to connection string

CHANGELOG.md, project.clj, src/tap_mssql/config.clj, src/tap_mssql/sync_strategies/full.clj, src/tap_mssql/sync_strategies/incremental.clj
Only add application intent read only to query-based replication methods, due to the lack of support of Change Tracking on secondary read replicas (this application intent forces all queries for the connection to a replica, if available).
The symptom of this situation is a message like the following:
```
For databases that are members of a secondary availability replica, change tracking is not supported. Run change tracking queries on the databases in the primary availability replica.
```
- None, I expect the automation to find any issues
Low, this is a reaction and fix for incorrectly documented behavior by Microsoft regarding #50
- revert this branch, bump patch, and re-release
=> v1.6.5: Only add read-only to query-based replication methods' connections

CHANGELOG.md, project.clj, src/tap_mssql/config.clj, src/tap_mssql/core.clj, src/tap_mssql/sync_strategies/full.clj, src/tap_mssql/sync_strategies/incremental.clj, test/tap_mssql/discover_config_test.clj
Because Full Table is used in Log-Based scenarios, and ChangeTracking (Log-Based Replication for tap-mssql) is generally used with secondary replicas, and mirrors, the current implementation is still not quite there.
The solution without having to deeply introspect the target server's infra somehow, then, is to catch exceptions while checking the connection, dissoc the ApplicationIntent in the event of a failure and retry once.
For posterity, this message can also occur when using ApplicationIntent ReadOnly where a mirror is configured:
```
Connecting to a mirrored SQL Server instance using the ApplicationIntent ReadOnly connection property is not supported.
```
Medium at this point, this is take 3, but this solution should be safer.
- revert this branch, bump patch, re-release
=> Retry on check-connection to use ApplicationIntent in all cases without error

CHANGELOG.md, project.clj, src/tap_mssql/config.clj, src/tap_mssql/sync_strategies/full.clj, src/tap_mssql/sync_strategies/incremental.clj, test/tap_mssql/discover_config_test.clj, test/tap_mssql/sync_log_based_test.clj, test/tap_mssql/test_utils.clj
In log-based syncing situations, the error won't get thrown when the tap calls `check-connection` with readonly metadata, because that is a valid query for `ApplicationIntent="ReadOnly"`. It instead fails when the change tracking tables are queried.
This splits the `config/->conn-map` function into two arities, one of which allows query-based syncs to attempt `ApplicationIntent="ReadOnly"` appropriately, the other allowing log-based to remain unchanged.
Added an integration test that sets up the scenario where the log-based query would throw, and it succeeds.
- N/A, went through and manually made the automated test we added fail.
Medium at this point, this will be round 3 of trying to get this right.
- revert back to 1.6.3, bump patch version, and re-release
=> Set readonly for query based with fallback

.circleci/config.yml
We are not getting the slack webhook from the circleci-user context in the build job of the cirlce workflow. Fix that.
=> add  circleci-user context to the build step

CHANGELOG.md, project.clj, src/tap_mssql/config.clj, src/tap_mssql/sync_strategies/full.clj, src/tap_mssql/sync_strategies/incremental.clj, src/tap_mssql/utils.clj, test/tap_mssql/try_read_only_utils_test.clj
In the epic read-only ApplicationIntent saga, it appears that the query being executed by the connection check doesn't always throw on the first time it's called. In this case, the read-only db-spec gets cached.
Additionally, the forms that throw are more complicated than just a `config/->conn-map` call, they are actual queries and/or JDBC query wrappers (specifically `jdbc/reducible-query`).
So, given these requirements, this PR adds an `if-let` style macro that takes a singular binding of a db-spec, a body of command(s) to run with that db-spec binding, and retries the body if it fails with `ApplicationIntent=ReadOnly` set.
- Successfully synced initial full table of a log-based replication for a database that was having the issue described above.
It's currently broken for this edge …
=> v1.6.8: Add macro to retry arbitrary code with a readonly db-spec

CHANGELOG.md, project.clj
Version bump for #62 
*  Update `nrepl` server binding from `0.0.0.0` to `127.0.0.1` [#62](https://github.com/stitchdata/tap-mssql/pull/62)
=> Bump to v1.6.10, update changelog

README.md
This PR adds instructions to install the `mssql-cli` tool. These instructions should work for most platforms.
The main reason I installed it via `pip` was because there's no official `apt` package for Ubuntu 20.04.
I ran through these steps myself.
- Low since this is just for local testing
=> Update README with `mssql-cli` install instructions

CHANGELOG.md, project.clj, src/tap_mssql/core.clj, tests/test_mssql_drop_multiple_tables.py, tests/test_mssql_log_based_no_pk.py
Updating log4j using singer-clojure due to vulnerability in [CVE-2020-9493](https://github.com/advisories/GHSA-prp9-9gxw-38j8) for TDL-21424
- Low
=> Version 1.6.11: Update log4j using singer-clojure

src/tap_mssql/catalog.clj, test/tap_mssql/discover_populated_catalog_datatyping_test.clj, tests/spec.py, tests/test_full_table_interrupted.py, tests/test_sync_full_names.py, tests/test_sync_full_pks.py, tests/test_sync_full_strings.py, tests/test_sync_incremental_pks.py, tests/test_sync_logical_names.py, tests/test_sync_logical_pks.py
This PR removes `maxLength` from the JSON schema.
- Low. Schema validation can fail when we include these values, but it's seems to be stricter than MSSQL is. There's no value in the tap complaining some value looks wrong when the database says the same thing
=> Remove `maxLength` from the catalog

CHANGELOG.md, project.clj
This is the version bump for #88 
See #88  
See #88 
- revert #88 and bump the version
=> Bump to v1.7.0, update changelog
